export const PostData = [
  {
    type: "free",
    title: "제목제목제목제목제목제목제목제목제목제목제목제목제목제목제목",
    content:
      "게시글 내용입니다. 게시글 내용입니다. 게시글 내용입니다. 게시글 내용입니다. 게시글 내용입니다.",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 2,
    hours: 3,
    minutes: 1,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "free",
    title: "제목2",
    content: "게시글 내용입니다.",
    univ: "00대학교",
    major: "기계공학과",
    year: 2023,
    month: 7,
    date: 2,
    hours: 14,
    minutes: 30,
    like: 10,
    star: 100,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "free",
    title: "제목3",
    content: "게시글 내용입니다.",
    univ: "00대학교",
    major: "영어영문학과",
    year: 2022,
    month: 9,
    date: 2,
    hours: 14,
    minutes: 30,
    like: 1,
    star: 10,
    comment: 150,
    imgSrc: [""],
  },
  {
    type: "freshman",
    title: "제목1",
    content: "게시글 내용입니다.",
    univ: "00대학교",
    major: "전자공학과",
    year: 2023,
    month: 9,
    date: 2,
    hours: 14,
    minutes: 30,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "freshman",
    title: "제목2",
    content:
      "게시글 내용입니다. 게시글 내용입니다. 게시글 내용입니다. 게시글 내용입니다. 게시글 내용입니다.",
    univ: "00대학교",
    major: "디지털미디어학과",
    year: 2023,
    month: 9,
    date: 2,
    hours: 2,
    minutes: 30,
    like: 10,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "date",
    title: "제목1",
    content: "게시글 내용입니다.",
    univ: "00대학교",
    major: "전자공학과",
    year: 2023,
    month: 9,
    date: 2,
    hours: 14,
    minutes: 30,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "promotion",
    title: "제목1",
    content: "게시글 내용입니다.",
    univ: "00대학교",
    major: "전자공학과",
    year: 2023,
    month: 9,
    date: 2,
    hours: 14,
    minutes: 30,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "popular",
    title: "제목1",
    content: "게시글 내용입니다.",
    univ: "00대학교",
    major: "전자공학과",
    year: 2023,
    month: 9,
    date: 2,
    hours: 14,
    minutes: 30,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
];
