export const PostData2 = [
  {
    type: "Medical",
    subType: "1",
    title: "의학 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Medical",
    subType: "2",
    title: "의학 제목2",
    content: "게시글 내용2",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "ArtsAthletics",
    subType: "1",
    title: "예체능 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Engineering",
    subType: "1",
    title: "공학 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Engineering",
    subType: "1",
    title: "공학 제목2",
    content: "게시글 내용2",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Engineering",
    subType: "2",
    title: "공학 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "NaturalScience",
    subType: "1",
    title: "자연 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "NaturalScience",
    subType: "3",
    title: "자연 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "LiberalArts",
    subType: "2",
    title: "인문 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "LiberalArts",
    subType: "1",
    title: "인문 제목2",
    content: "게시글 내용2",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Social",
    subType: "1",
    title: "사회 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Social",
    subType: "2",
    title: "사회 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Education",
    subType: "1",
    title: "교육 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Education",
    subType: "1",
    title: "교육 제목2",
    content: "게시글 내용2",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
  {
    type: "Education",
    subType: "4",
    title: "교육 제목1",
    content: "게시글 내용1",
    univ: "00대학교",
    major: "소프트웨어학과",
    year: 2023,
    month: 9,
    date: 5,
    hours: 1,
    minutes: 2,
    like: 999,
    star: 10,
    comment: 15,
    imgSrc: [""],
  },
];
